### ISSUE TITLE
KCP and Cert Manager are fighting over labels causing many update events

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kcp-glbc#288] opened 2022-07-21 11:51 UTC
Priority:Medium

## Expected Behavior
* tls secrets in the GLBC workspace don't need to be synced

## Actual Behavior
* KCP and Cert manager are fighting with each other over labels. KCP adds a scheduling label and cert manager removes it

### Steps to Reproduce the Problem

1. use GLBC and watch the secret created by cert manager in the cert-manager ns

## Suggested Resolution
* move certs to a new ns and disable syncing for that ns

**Comment by jasonmadigan** [comment] 2022-08-03 15:08
Might be related to #312

**Comment by david-martin** [comment] 2022-08-04 08:11
Going to look at this as part of #309

**Comment by david-martin** [comment] 2022-08-04 11:42
Closing this as cannot reproduce.
The comparison check added in https://github.com/Kuadrant/kcp-glbc/blob/06b563b0466bce16b9d82eb6578ac2902d12c8a4/pkg/reconciler/ingress/controller.go#L165 fixed the repeated requeueing, but also prevented the UpdateFunc being called repeatedly.

Unecessary labels will still be removed in #312, but that has no bearing on this issue anymore

**Closed by david-martin** 2022-08-04 11:42 UTC
Labels: kind/bug
